#!/usr/bin/env bash
# Local dev chain: anvil fork of Robinhood Chain mainnet (chainId 4663, real Uniswap v4) + Lancio contracts.
# Writes web/.env.development.local and indexer/.env.local with the deployed addresses.
# Usage: scripts/dev-chain.sh            (Ctrl+C stops anvil)
set -euo pipefail
export PATH="$PATH:$HOME/.foundry/bin"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RPC=http://127.0.0.1:8545
FORK_URL="${RPC_URL_4663:-https://rpc.mainnet.chain.robinhood.com}"

if ! cast chain-id --rpc-url $RPC >/dev/null 2>&1; then
  # --hardfork cancun: skips the EIP-2935 blockhash system call, which needs historical state the public RPC prunes after ~10 min
  anvil --fork-url "$FORK_URL" --port 8545 --host 127.0.0.1 --block-time 1 --hardfork cancun > /tmp/lancio-anvil.log 2>&1 &
  ANVIL_PID=$!
  trap 'kill $ANVIL_PID 2>/dev/null' EXIT
  until cast chain-id --rpc-url $RPC >/dev/null 2>&1; do sleep 0.5; done
fi

# anvil default account #0 (public test key — local only)
PK=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
export PROTOCOL_OWNER=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
export PROTOCOL_TREASURY=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
export DEPLOY_NAME=local
START=$(cast block-number --rpc-url $RPC)
(cd "$ROOT/contracts" && forge script script/Deploy.s.sol --rpc-url $RPC --broadcast --private-key $PK >/dev/null)

J="$ROOT/contracts/deployments/local.json"
get() { python3 -c "import json;print(json.load(open('$J'))['$1'])"; }
LP=$(get launchpad); LOCKER=$(get locker); HOOK=$(get hook)

cat > "$ROOT/web/.env.development.local" <<ENV
# generated by scripts/dev-chain.sh — local anvil fork
NEXT_PUBLIC_USE_MOCKS=false
NEXT_PUBLIC_RPC_URL=$RPC
NEXT_PUBLIC_LAUNCHPAD=$LP
NEXT_PUBLIC_LOCKER=$LOCKER
NEXT_PUBLIC_HOOK=$HOOK
NEXT_PUBLIC_START_BLOCK=$START
ENV
cat > "$ROOT/indexer/.env.local" <<ENV
# generated by scripts/dev-chain.sh — local anvil fork
PONDER_RPC_URL_4663=$RPC
LAUNCHPAD_ADDRESS=$LP
LOCKER_ADDRESS=$LOCKER
HOOK_ADDRESS=$HOOK
START_BLOCK=$START
ALLOW_LOCAL_METADATA=true
ENV
echo "Lancio local chain ready: launchpad $LP  locker $LOCKER  hook $HOOK  startBlock $START"
echo "Test wallets: import anvil keys from /tmp/lancio-anvil.log into your wallet, network RPC $RPC, chainId 4663."
if [ -n "${ANVIL_PID:-}" ]; then wait $ANVIL_PID; fi
